export default [
  {
    id: 1,
    name: 'Service 1',
    position: { lat: 43.69, lng: -79.43 },
    rating: 4.0,
    type: ['Paper', 'Glass', 'Clothes'],
    option: 'Free',
  },
  {
    id: 2,
    name: 'Service 2',
    position: { lat: 44.69, lng: -79.73 },
    rating: 4.9,
    type: ['Glass', 'Metal'],
    option: 'Free',
  },
  {
    id: 3,
    name: 'Service 3',
    position: { lat: 42.99, lng: -79.93 },
    rating: 4.8,
    type: ['Metal'],
    option: 'Paid',
  },
  {
    id: 4,
    name: 'Service 4',
    position: { lat: 44.19, lng: -78.73 },
    rating: 4.2,
    type: ['Electric', 'Metal'],
    option: 'Paid',
  },
  {
    id: 5,
    name: 'Service 5',
    position: { lat: 44.39, lng: -78.23 },
    rating: 4.5,
    type: ['Paper', 'Organic'],
    option: 'Paid',
  },
];
